package problems

import math.pow

/**
 * http://projecteuler.net/problem=29
 *
 * How many distinct terms are in the sequence generated by a^b for 2  a  100 and 2  b  100?
 */
object Problem_0029 extends Problem {

  val terms = for {
    base <- 2 to 100
    exp <- 2 to 100
  } yield pow(base, exp)

  def answer = terms.toSet.size

}